name: screenbridge
description: Screenshot sync between mobile and desktop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  receive_sharing_intent: ^1.8.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
